import {
  faDoorOpen,
  faLock,
  faMountainSun,
  faSnowflake,
  faSun,
  faTree,
} from "@fortawesome/free-solid-svg-icons";

export const tables = [
  /* GARDEN AREA - OUTDOOR */
  {
    id: 21,
    area: "outdoor",
    seats: 4,
    available: true,
    type: "round",
    x: "20%",
    y: "17%",
  },
  {
    id: 22,
    area: "outdoor",
    seats: 4,
    available: true,
    type: "round",
    x: "35%",
    y: "17%",
  },
  {
    id: 23,
    area: "outdoor",
    seats: 4,
    available: true,
    type: "round",
    x: "55%",
    y: "17%",
  },
  {
    id: 24,
    area: "outdoor",
    seats: 4,
    available: true,
    type: "round",
    x: "70%",
    y: "17%",
  },

  /* MAIN DINING - LEFT */
  {
    id: 11,
    area: "indoor",
    seats: 4,
    available: true,
    type: "square",
    x: "10%",
    y: "40%",
  },
  {
    id: 12,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "20%",
    y: "40%",
  },
  {
    id: 13,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "10%",
    y: "55%",
  },
  {
    id: 14,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "20%",
    y: "55%",
  },
  {
    id: 15,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "10%",
    y: "70%",
  },
  {
    id: 16,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "20%",
    y: "70%",
  },

  /* MAIN DINING - CENTER */
  {
    id: 17,
    area: "indoor",
    seats: 6,
    available: true,
    type: "round",
    x: "35%",
    y: "63%",
  },
  {
    id: 18,
    area: "indoor",
    seats: 6,
    available: true,
    type: "round",
    x: "55%",
    y: "63%",
  },
  {
    id: 5,
    area: "indoor",
    seats: 3,
    available: true,
    type: "round",
    x: "45%",
    y: "47%",
  },

  /* MAIN DINING - RIGHT */
  {
    id: 19,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "70%",
    y: "40%",
  },
  {
    id: 20,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "80%",
    y: "40%",
  },
  {
    id: 10,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "70%",
    y: "55%",
  },
  {
    id: 9,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "80%",
    y: "55%",
  },
  {
    id: 8,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "70%",
    y: "70%",
  },
  {
    id: 7,
    area: "indoor",
    seats: 2,
    available: true,
    type: "square",
    x: "80%",
    y: "70%",
  },

  /* LOUNGE AREA */
  {
    id: 1,
    area: "lounge",
    seats: 4,
    available: true,
    type: "round",
    x: "30%",
    y: "91%",
  },
  {
    id: 2,
    area: "lounge",
    seats: 4,
    available: true,
    type: "round",
    x: "43%",
    y: "91%",
  },
  {
    id: 3,
    area: "lounge",
    seats: 4,
    available: true,
    type: "round",
    x: "56%",
    y: "91%",
  },
  {
    id: 4,
    area: "lounge",
    seats: 4,
    available: true,
    type: "round",
    x: "69%",
    y: "91%",
  },
];

export const privateRooms = [
  { id: "P1", seats: 6, available: true },
  { id: "P2", seats: 8, available: true },
  { id: "P3", seats: 10, available: true },
];

export const rooms = [
  {
    id: "main-dining",
    name: "Main Dining Room",
    type: "Indoor",
    capacity: "10 - 24 Guests",
    minGuests: 10,
    maxGuests: 24,
    available: true,
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80",
    description:
      "Spacious indoor area perfect for business meetings, family gatherings, or special celebrations.",
    features: [
      { icon: faDoorOpen, label: "Indoor" },
      { icon: faSnowflake, label: "Air Conditioned" },
      { icon: faLock, label: "Private Area" },
    ],
  },
  {
    id: "garden",
    name: "Garden Area",
    type: "Outdoor",
    capacity: "10 - 28 Guests",
    minGuests: 10,
    maxGuests: 28,
    available: true,
    image:
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80",
    description:
      "Open air seating surrounded by greenery. Perfect for relaxed events and celebrations.",
    features: [
      { icon: faTree, label: "Outdoor" },
      { icon: faMountainSun, label: "Natural View" },
      { icon: faSun, label: "Fresh Air" },
    ],
  },
  {
    id: "private-1",
    name: "Private Room 1",
    type: "Private Room",
    capacity: "6 - 10 Guests",
    minGuests: 6,
    maxGuests: 10,
    available: true,
    image:
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80",
    description:
      "A cozy private room for intimate meetings, family dinners, or small celebrations.",
    features: [
      { icon: faDoorOpen, label: "Indoor" },
      { icon: faSnowflake, label: "Air Conditioned" },
      { icon: faLock, label: "Private" },
    ],
  },
  {
    id: "private-2",
    name: "Private Room 2",
    type: "Private Room",
    capacity: "8 - 16 Guests",
    minGuests: 8,
    maxGuests: 16,
    available: true,
    image:
      "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=900&q=80",
    description:
      "Comfortable private space for medium-sized events and business meetings.",
    features: [
      { icon: faDoorOpen, label: "Indoor" },
      { icon: faSnowflake, label: "Air Conditioned" },
      { icon: faLock, label: "Private" },
    ],
  },
];
